---
abstract: 'POE FILTR T SPEKK LIEK LOLCATZ. KTHNX!'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.84'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Filter-LOLCAT
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Acme::LOLCAT: 0
  POE: 1.004
  POE::Filter: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-filter-lolcat.git
version: 1.06
